'use client';

/**
 * DisclaimerBanner — NFR-26, NFR-27, NFR-29, NFR-30
 *
 * Persistent legal disclaimer shown on crop + services pages.
 * Collapsed to a slim strip after first acknowledgement (saved in localStorage).
 * 
 * Rule: ML predictions are advisory only — not a substitute for expert agronomic advice.
 */

import { useState, useEffect } from 'react';
import { AlertTriangle, ChevronDown, ChevronUp, X } from 'lucide-react';
import clsx from 'clsx';
import { useTranslation } from "react-i18next";


const STORAGE_KEY = 'cultivax_disclaimer_ack';

interface DisclaimerBannerProps {
  /** Contextual page name shown in the disclaimer */
  context?: 'crops' | 'services' | 'ml' | 'general';
  /** If true always shows full text (e.g. on first login) */
  forceExpand?: boolean;
}

const CONTEXT_TEXT: Record<string, string> = {
  crops:    'Crop health scores and risk predictions are generated by AI models and are for guidance only. Always consult a certified agronomist before taking action.',
  services: 'Service provider ratings are based on community feedback. CultivaX does not guarantee the quality or availability of any listed service.',
  ml:       'ML-based recommendations are probabilistic estimates. Actual crop outcomes depend on local conditions, weather, and farming practices.',
  general:  'CultivaX is an advisory platform. All predictions and recommendations are indicative only and do not constitute professional agricultural advice.',
};

export default function DisclaimerBanner({ context = 'general', forceExpand = false }: DisclaimerBannerProps) {
  const { t } = useTranslation();
  const [acknowledged, setAcknowledged] = useState(true);
  const [expanded, setExpanded]         = useState(false);

  useEffect(() => {
    const acked = localStorage.getItem(STORAGE_KEY);
    if (!acked || forceExpand) {
      setAcknowledged(false);
      setExpanded(true);
    }
  }, [forceExpand]);

  function acknowledge() {
    localStorage.setItem(STORAGE_KEY, '1');
    setAcknowledged(true);
    setExpanded(false);
  }

  if (acknowledged) {
    return (
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center justify-between px-4 py-2 bg-amber-950/30 border-b border-amber-900/30 text-xs text-amber-500 hover:bg-amber-950/50 transition-colors"
      >
        <span className="flex items-center gap-1.5">
          <AlertTriangle className="w-3 h-3" />
          Advisory disclaimer applies to all predictions
        </span>
        {expanded ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
      </button>
    );
  }

  return (
    <div className={clsx(
      'border-b border-amber-800/40 bg-amber-950/20 px-4 py-3 transition-all',
      expanded ? 'block' : 'hidden',
    )}>
      <div className="max-w-3xl mx-auto flex items-start gap-3">
        <AlertTriangle className="w-4 h-4 text-amber-400 flex-shrink-0 mt-0.5" />
        <div className="flex-1 min-w-0 space-y-1">
          <p className="text-xs font-semibold text-amber-300">{t('crops.advisory_notice', 'Advisory Notice')}</p>
          <p className="text-xs text-amber-200/80 leading-relaxed">{t('crops.advisory_text', CONTEXT_TEXT[context])}</p>
          <p className="text-[10px] text-amber-300/50">
            {t('crops.advisory_subtext', 'By continuing to use CultivaX, you acknowledge that recommendations are AI-assisted and should be validated by qualified professionals before implementation.')}
          </p>
        </div>
        <button
          onClick={acknowledge}
          className="flex-shrink-0 px-3 py-1.5 rounded-lg bg-amber-700 hover:bg-amber-600 text-white text-xs font-semibold transition-colors"
        >
          {t('crops.advisory_got_it', 'Got it')}
        </button>
      </div>
    </div>
  );
}
