"""Add missing tables for Phase 3

Revision ID: 1322ed74ac86
Revises: dcc0e430a10a
Create Date: 2026-04-10 07:10:26.151473
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1322ed74ac86'
down_revision: Union[str, None] = 'dcc0e430a10a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispute_cases',
    sa.Column('reporter_id', sa.UUID(), nullable=True),
    sa.Column('respondent_id', sa.UUID(), nullable=True),
    sa.Column('service_request_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispute_cases_assigned_to'), 'dispute_cases', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_dispute_cases_is_deleted'), 'dispute_cases', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dispute_cases_reporter_id'), 'dispute_cases', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_dispute_cases_respondent_id'), 'dispute_cases', ['respondent_id'], unique=False)
    op.create_index(op.f('ix_dispute_cases_service_request_id'), 'dispute_cases', ['service_request_id'], unique=False)
    op.create_index(op.f('ix_dispute_cases_status'), 'dispute_cases', ['status'], unique=False)
    op.create_table('official_schemes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('portal_url', sa.String(length=2000), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('crop_type', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_official_schemes_category'), 'official_schemes', ['category'], unique=False)
    op.create_index(op.f('ix_official_schemes_crop_type'), 'official_schemes', ['crop_type'], unique=False)
    op.create_index(op.f('ix_official_schemes_is_deleted'), 'official_schemes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_official_schemes_name'), 'official_schemes', ['name'], unique=False)
    op.create_index(op.f('ix_official_schemes_region'), 'official_schemes', ['region'], unique=False)
    op.create_table('sms_delivery_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('message_template', sa.String(length=100), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_response', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_delivery_logs_is_deleted'), 'sms_delivery_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sms_delivery_logs_status'), 'sms_delivery_logs', ['status'], unique=False)
    op.create_index(op.f('ix_sms_delivery_logs_user_id'), 'sms_delivery_logs', ['user_id'], unique=False)
    op.create_table('user_consents',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_consents_is_deleted'), 'user_consents', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_consents_user_id'), 'user_consents', ['user_id'], unique=False)
    op.create_table('scheme_redirect_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('scheme_id', sa.UUID(), nullable=False),
    sa.Column('redirect_url', sa.String(length=2000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['official_schemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheme_redirect_logs_is_deleted'), 'scheme_redirect_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_scheme_redirect_logs_scheme_id'), 'scheme_redirect_logs', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_scheme_redirect_logs_user_id'), 'scheme_redirect_logs', ['user_id'], unique=False)
    op.create_table('ml_inference_audit',
    sa.Column('crop_instance_id', sa.UUID(), nullable=True),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('inference_source', sa.String(length=50), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prediction_value', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('risk_label', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['crop_instance_id'], ['crop_instances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_inference_audit_crop_instance_id'), 'ml_inference_audit', ['crop_instance_id'], unique=False)
    op.create_index('ix_ml_inference_audit_crop_model', 'ml_inference_audit', ['crop_instance_id', 'model_id'], unique=False)
    op.create_index(op.f('ix_ml_inference_audit_is_deleted'), 'ml_inference_audit', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ml_inference_audit_model_id'), 'ml_inference_audit', ['model_id'], unique=False)
    op.create_index(op.f('ix_ml_inference_audit_model_version'), 'ml_inference_audit', ['model_version'], unique=False)
    op.create_index('ix_ml_inference_audit_version', 'ml_inference_audit', ['model_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ml_inference_audit_version', table_name='ml_inference_audit')
    op.drop_index(op.f('ix_ml_inference_audit_model_version'), table_name='ml_inference_audit')
    op.drop_index(op.f('ix_ml_inference_audit_model_id'), table_name='ml_inference_audit')
    op.drop_index(op.f('ix_ml_inference_audit_is_deleted'), table_name='ml_inference_audit')
    op.drop_index('ix_ml_inference_audit_crop_model', table_name='ml_inference_audit')
    op.drop_index(op.f('ix_ml_inference_audit_crop_instance_id'), table_name='ml_inference_audit')
    op.drop_table('ml_inference_audit')
    op.drop_index(op.f('ix_scheme_redirect_logs_user_id'), table_name='scheme_redirect_logs')
    op.drop_index(op.f('ix_scheme_redirect_logs_scheme_id'), table_name='scheme_redirect_logs')
    op.drop_index(op.f('ix_scheme_redirect_logs_is_deleted'), table_name='scheme_redirect_logs')
    op.drop_table('scheme_redirect_logs')
    op.drop_index(op.f('ix_user_consents_user_id'), table_name='user_consents')
    op.drop_index(op.f('ix_user_consents_is_deleted'), table_name='user_consents')
    op.drop_table('user_consents')
    op.drop_index(op.f('ix_sms_delivery_logs_user_id'), table_name='sms_delivery_logs')
    op.drop_index(op.f('ix_sms_delivery_logs_status'), table_name='sms_delivery_logs')
    op.drop_index(op.f('ix_sms_delivery_logs_is_deleted'), table_name='sms_delivery_logs')
    op.drop_table('sms_delivery_logs')
    op.drop_index(op.f('ix_official_schemes_region'), table_name='official_schemes')
    op.drop_index(op.f('ix_official_schemes_name'), table_name='official_schemes')
    op.drop_index(op.f('ix_official_schemes_is_deleted'), table_name='official_schemes')
    op.drop_index(op.f('ix_official_schemes_crop_type'), table_name='official_schemes')
    op.drop_index(op.f('ix_official_schemes_category'), table_name='official_schemes')
    op.drop_table('official_schemes')
    op.drop_index(op.f('ix_dispute_cases_status'), table_name='dispute_cases')
    op.drop_index(op.f('ix_dispute_cases_service_request_id'), table_name='dispute_cases')
    op.drop_index(op.f('ix_dispute_cases_respondent_id'), table_name='dispute_cases')
    op.drop_index(op.f('ix_dispute_cases_reporter_id'), table_name='dispute_cases')
    op.drop_index(op.f('ix_dispute_cases_is_deleted'), table_name='dispute_cases')
    op.drop_index(op.f('ix_dispute_cases_assigned_to'), table_name='dispute_cases')
    op.drop_table('dispute_cases')
    # ### end Alembic commands ###
