"""add_phase5_models

Revision ID: 3756dbe029b1
Revises: a2b8bdff486e
Create Date: 2026-04-09 02:10:32.462373
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3756dbe029b1'
down_revision: Union[str, None] = 'a2b8bdff486e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_configs',
    sa.Column('region_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_region_configs_is_deleted'), 'region_configs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_region_configs_region_name'), 'region_configs', ['region_name'], unique=True)
    op.create_table('user_reports',
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reported_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_reports_is_deleted'), 'user_reports', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_reports_reported_id'), 'user_reports', ['reported_id'], unique=False)
    op.create_index(op.f('ix_user_reports_reporter_id'), 'user_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_user_reports_status'), 'user_reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_reports_status'), table_name='user_reports')
    op.drop_index(op.f('ix_user_reports_reporter_id'), table_name='user_reports')
    op.drop_index(op.f('ix_user_reports_reported_id'), table_name='user_reports')
    op.drop_index(op.f('ix_user_reports_is_deleted'), table_name='user_reports')
    op.drop_table('user_reports')
    op.drop_index(op.f('ix_region_configs_region_name'), table_name='region_configs')
    op.drop_index(op.f('ix_region_configs_is_deleted'), table_name='region_configs')
    op.drop_table('region_configs')
    # ### end Alembic commands ###
