"""audit_check

Revision ID: 6afd114c0415
Revises: 77f998216d3c
Create Date: 2026-04-04 16:24:55.541075
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6afd114c0415'
down_revision: Union[str, None] = '77f998216d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_log', sa.Column('last_error', sa.String(length=2000), nullable=True))
    op.add_column('event_log', sa.Column('last_failed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('event_log', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_event_log_next_retry_at'), 'event_log', ['next_retry_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_log_next_retry_at'), table_name='event_log')
    op.drop_column('event_log', 'next_retry_at')
    op.drop_column('event_log', 'last_failed_at')
    op.drop_column('event_log', 'last_error')
    # ### end Alembic commands ###
