"""Add ExposureLog Model

Revision ID: 77f998216d3c
Revises: 8f17bcff42a4
Create Date: 2026-04-04 12:16:19.580007
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '77f998216d3c'
down_revision: Union[str, None] = '8f17bcff42a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exposure_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('search_signature_hash', sa.String(length=64), nullable=True),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('shown_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exposure_logs_provider_shown', 'exposure_logs', ['provider_id', 'shown_at'], unique=False)
    op.create_index('ix_exposure_logs_region_shown', 'exposure_logs', ['region', 'shown_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exposure_logs_region_shown', table_name='exposure_logs')
    op.drop_index('ix_exposure_logs_provider_shown', table_name='exposure_logs')
    op.drop_table('exposure_logs')
    # ### end Alembic commands ###
