"""Align ServiceRequest and ServiceReview with schema

Revision ID: 8f17bcff42a4
Revises: 9f77b8ff0fff
Create Date: 2026-04-03 21:08:32.946657
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8f17bcff42a4'
down_revision: Union[str, None] = '9f77b8ff0fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_requests', sa.Column('crop_instance_id', sa.UUID(), nullable=True))
    op.add_column('service_requests', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('service_requests', sa.Column('urgency', sa.String(length=50), nullable=True))
    op.add_column('service_requests', sa.Column('preferred_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('service_requests', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'service_requests', 'crop_instances', ['crop_instance_id'], ['id'])
    op.drop_column('service_requests', 'crop_type')
    op.drop_column('service_requests', 'completed_date')
    op.drop_column('service_requests', 'requested_date')
    op.add_column('service_reviews', sa.Column('provider_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_service_reviews_provider_id'), 'service_reviews', ['provider_id'], unique=False)
    op.create_foreign_key(None, 'service_reviews', 'service_providers', ['provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_reviews', type_='foreignkey')
    op.drop_index(op.f('ix_service_reviews_provider_id'), table_name='service_reviews')
    op.drop_column('service_reviews', 'provider_id')
    op.add_column('service_requests', sa.Column('requested_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('service_requests', sa.Column('completed_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('service_requests', sa.Column('crop_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'service_requests', type_='foreignkey')
    op.drop_column('service_requests', 'completed_at')
    op.drop_column('service_requests', 'preferred_date')
    op.drop_column('service_requests', 'urgency')
    op.drop_column('service_requests', 'region')
    op.drop_column('service_requests', 'crop_instance_id')
    # ### end Alembic commands ###
