"""Extend media_file with ingest and dedup fields

Revision ID: 9f77b8ff0fff
Revises: e677fbcaeaf3
Create Date: 2026-04-01 23:28:41.445471
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9f77b8ff0fff'
down_revision: Union[str, None] = 'e677fbcaeaf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('checksum_sha256', sa.String(length=64), nullable=True))
    op.add_column('media_files', sa.Column('source_channel', sa.String(length=20), nullable=True))
    op.add_column('media_files', sa.Column('capture_lat', sa.Float(), nullable=True))
    op.add_column('media_files', sa.Column('capture_lng', sa.Float(), nullable=True))
    op.add_column('media_files', sa.Column('is_quarantined', sa.Boolean(), nullable=True))
    op.create_index('ix_media_crop_created', 'media_files', ['crop_instance_id', 'created_at', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_media_files_checksum_sha256'), 'media_files', ['checksum_sha256'], unique=False)
    op.create_index('ix_media_status', 'media_files', ['analysis_status', 'deleted_at'], unique=False)
    op.create_unique_constraint('uq_media_checksum_per_crop', 'media_files', ['crop_instance_id', 'checksum_sha256'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_media_checksum_per_crop', 'media_files', type_='unique')
    op.drop_index('ix_media_status', table_name='media_files')
    op.drop_index(op.f('ix_media_files_checksum_sha256'), table_name='media_files')
    op.drop_index('ix_media_crop_created', table_name='media_files')
    op.drop_column('media_files', 'is_quarantined')
    op.drop_column('media_files', 'capture_lng')
    op.drop_column('media_files', 'capture_lat')
    op.drop_column('media_files', 'source_channel')
    op.drop_column('media_files', 'checksum_sha256')
    # ### end Alembic commands ###
