"""add_user_consents_phase3

Revision ID: a2b8bdff486e
Revises: a9263c2f5e1e
Create Date: 2026-04-09 01:51:09.508690
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a2b8bdff486e'
down_revision: Union[str, None] = 'a9263c2f5e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
