"""add_schemes_disputes_sms

Revision ID: a9263c2f5e1e
Revises: f9fb64385d37
Create Date: 2026-04-09 01:22:24.170130
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a9263c2f5e1e'
down_revision: Union[str, None] = 'f9fb64385d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
