"""auto fix missing tables

Revision ID: bda0371cbd0b
Revises: 3756dbe029b1
Create Date: 2026-04-09 12:28:47.757442
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'bda0371cbd0b'
down_revision: Union[str, None] = '3756dbe029b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
