"""weather_snapshots

Revision ID: e677fbcaeaf3
Revises: 011
Create Date: 2026-04-01 23:08:15.041311
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e677fbcaeaf3'
down_revision: Union[str, None] = '011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_key', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('provider_source', sa.String(), nullable=False),
    sa.Column('weather_payload_json', sa.JSON(), nullable=False),
    sa.Column('weather_risk_score', sa.Float(), nullable=False),
    sa.Column('alerts_json', sa.JSON(), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_snapshots_captured_at'), 'weather_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_weather_snapshots_expires_at'), 'weather_snapshots', ['expires_at'], unique=False)
    op.create_index(op.f('ix_weather_snapshots_location_key'), 'weather_snapshots', ['location_key'], unique=False)
    op.drop_index('ix_active_sessions_is_revoked', table_name='active_sessions')
    op.drop_index('ix_active_sessions_refresh_token_hash', table_name='active_sessions')
    op.drop_index('ix_active_sessions_user_id', table_name='active_sessions')
    op.drop_table('active_sessions')
    op.drop_index('ix_otp_codes_phone', table_name='otp_codes')
    op.drop_table('otp_codes')
    op.alter_column('abuse_flags', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'low'::character varying"))
    op.alter_column('abuse_flags', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('abuse_flags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('abuse_flags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('abuse_flags', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_abuse_flags_farmer_id'), 'abuse_flags', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_abuse_flags_flag_type'), 'abuse_flags', ['flag_type'], unique=False)
    op.create_index(op.f('ix_abuse_flags_is_deleted'), 'abuse_flags', ['is_deleted'], unique=False)
    op.alter_column('action_logs', 'action_impact_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Operational'::character varying"))
    op.alter_column('action_logs', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'web'::character varying"))
    op.alter_column('action_logs', 'is_override',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('action_logs', 'is_orphaned',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('action_logs', 'server_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('action_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('action_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('action_logs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_action_logs_is_deleted'), 'action_logs', ['is_deleted'], unique=False)
    op.alter_column('admin_audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('admin_audit_log', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('admin_audit_log', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_admin_audit_log_action'), 'admin_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_admin_id'), 'admin_audit_log', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_is_deleted'), 'admin_audit_log', ['is_deleted'], unique=False)
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'info'::character varying"))
    op.alter_column('alerts', 'is_acknowledged',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('alerts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('alerts', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_alerts_is_deleted'), 'alerts', ['is_deleted'], unique=False)
    op.alter_column('backup_verification_logs', 'backup_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_verification_logs', 'backup_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'full'::character varying"))
    op.alter_column('backup_verification_logs', 'restore_tested',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('backup_verification_logs', 'result',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('backup_verification_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_verification_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_verification_logs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_backup_verification_logs_is_deleted'), 'backup_verification_logs', ['is_deleted'], unique=False)
    op.alter_column('crop_instance_snapshots', 'snapshot_version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('crop_instance_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('crop_instance_snapshots', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('crop_instance_snapshots', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_crop_instance_snapshots_crop_instance_id'), 'crop_instance_snapshots', ['crop_instance_id'], unique=False)
    op.create_index(op.f('ix_crop_instance_snapshots_is_deleted'), 'crop_instance_snapshots', ['is_deleted'], unique=False)
    op.add_column('crop_instances', sa.Column('projected_harvest_date', sa.Date(), nullable=True))
    op.alter_column('crop_instances', 'stress_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('crop_instances', 'risk_index',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('crop_instances', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('crop_instances', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('crop_instances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('crop_instances', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_crop_instances_land_parcel_id', table_name='crop_instances')
    op.create_index(op.f('ix_crop_instances_is_deleted'), 'crop_instances', ['is_deleted'], unique=False)
    op.add_column('crop_rule_templates', sa.Column('status', sa.String(length=20), nullable=False, comment='draft → validated → active → deprecated'))
    op.add_column('crop_rule_templates', sa.Column('approved_by', sa.UUID(), nullable=True, comment='Second admin who approved'))
    op.add_column('crop_rule_templates', sa.Column('approved_at', sa.DateTime(), nullable=True, comment='Approval timestamp'))
    op.add_column('crop_rule_templates', sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Validation result details'))
    op.alter_column('crop_rule_templates', 'stage_definitions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('crop_rule_templates', 'risk_parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('crop_rule_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('crop_rule_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('crop_rule_templates', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_crop_rule_templates_is_deleted'), 'crop_rule_templates', ['is_deleted'], unique=False)
    op.drop_column('crop_rule_templates', 'is_active')
    op.alter_column('deviation_profile_archive', 'archived_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('deviation_profile_archive', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('deviation_profile_archive', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('deviation_profile_archive', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_deviation_archive_farmer', table_name='deviation_profile_archive')
    op.create_index(op.f('ix_deviation_profile_archive_farmer_id'), 'deviation_profile_archive', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_deviation_profile_archive_is_deleted'), 'deviation_profile_archive', ['is_deleted'], unique=False)
    op.alter_column('deviation_profiles', 'consecutive_deviation_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('deviation_profiles', 'deviation_trend_slope',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('deviation_profiles', 'recurring_pattern_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('deviation_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('deviation_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('deviation_profiles', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint('deviation_profiles_crop_instance_id_key', 'deviation_profiles', type_='unique')
    op.create_index(op.f('ix_deviation_profiles_crop_instance_id'), 'deviation_profiles', ['crop_instance_id'], unique=True)
    op.create_index(op.f('ix_deviation_profiles_is_deleted'), 'deviation_profiles', ['is_deleted'], unique=False)
    op.alter_column('equipment', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('equipment', 'condition',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'good'::character varying"))
    op.alter_column('equipment', 'is_flagged',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('equipment', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('equipment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('equipment', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_equipment_is_deleted'), 'equipment', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_equipment_provider_id'), 'equipment', ['provider_id'], unique=False)
    op.alter_column('event_log', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('event_log', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('event_log', 'schema_version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('event_log', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('event_log', 'max_retries',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('event_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('event_log', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('event_log', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_event_log_entity_id'), 'event_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_event_log_event_type'), 'event_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_log_is_deleted'), 'event_log', ['is_deleted'], unique=False)
    op.alter_column('farmer_action_audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('farmer_action_audit_log', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('farmer_action_audit_log', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_farmer_audit_action', table_name='farmer_action_audit_log')
    op.drop_index('ix_farmer_audit_farmer', table_name='farmer_action_audit_log')
    op.create_index(op.f('ix_farmer_action_audit_log_action_type'), 'farmer_action_audit_log', ['action_type'], unique=False)
    op.create_index(op.f('ix_farmer_action_audit_log_farmer_id'), 'farmer_action_audit_log', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_farmer_action_audit_log_is_deleted'), 'farmer_action_audit_log', ['is_deleted'], unique=False)
    op.alter_column('feature_flags', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('feature_flags', 'scope',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'global'::character varying"))
    op.alter_column('feature_flags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('feature_flags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('feature_flags', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint('feature_flags_flag_name_key', 'feature_flags', type_='unique')
    op.create_index(op.f('ix_feature_flags_flag_name'), 'feature_flags', ['flag_name'], unique=True)
    op.create_index(op.f('ix_feature_flags_is_deleted'), 'feature_flags', ['is_deleted'], unique=False)
    op.alter_column('labor', 'available_units',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('labor', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('labor', 'is_flagged',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('labor', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('labor', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('labor', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_labor_provider', table_name='labor')
    op.create_index(op.f('ix_labor_is_deleted'), 'labor', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_labor_provider_id'), 'labor', ['provider_id'], unique=False)
    op.alter_column('land_parcels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('land_parcels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('land_parcels', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_land_parcels_farmer', table_name='land_parcels')
    op.create_index(op.f('ix_land_parcels_farmer_id'), 'land_parcels', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_land_parcels_is_deleted'), 'land_parcels', ['is_deleted'], unique=False)
    op.alter_column('market_prices', 'unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'kg'::character varying"))
    op.alter_column('market_prices', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'INR'::character varying"))
    op.alter_column('market_prices', 'is_stale',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('market_prices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('market_prices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('market_prices', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_market_prices_crop', table_name='market_prices')
    op.create_index(op.f('ix_market_prices_crop_type'), 'market_prices', ['crop_type'], unique=False)
    op.create_index(op.f('ix_market_prices_is_deleted'), 'market_prices', ['is_deleted'], unique=False)
    op.alter_column('media_files', 'analysis_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('media_files', 'geo_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('media_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('media_files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('media_files', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_media_files_crop_instance_id'), 'media_files', ['crop_instance_id'], unique=False)
    op.create_index(op.f('ix_media_files_is_deleted'), 'media_files', ['is_deleted'], unique=False)
    op.alter_column('ml_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ml_feedback', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ml_feedback', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_ml_feedback_crop', table_name='ml_feedback')
    op.create_index(op.f('ix_ml_feedback_crop_instance_id'), 'ml_feedback', ['crop_instance_id'], unique=False)
    op.create_index(op.f('ix_ml_feedback_is_deleted'), 'ml_feedback', ['is_deleted'], unique=False)
    op.alter_column('ml_models', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('ml_models', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('ml_models', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ml_models', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ml_models', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_ml_models_is_deleted'), 'ml_models', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ml_models_model_name'), 'ml_models', ['model_name'], unique=False)
    op.alter_column('ml_training_audit', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ml_training_audit', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ml_training_audit', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_ml_training_audit_is_deleted'), 'ml_training_audit', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ml_training_audit_model_id'), 'ml_training_audit', ['model_id'], unique=False)
    op.alter_column('pest_alert_history', 'alert_level',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Low'::character varying"))
    op.alter_column('pest_alert_history', 'detected_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('pest_alert_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pest_alert_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pest_alert_history', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_pest_alert_crop', table_name='pest_alert_history')
    op.create_index(op.f('ix_pest_alert_history_crop_instance_id'), 'pest_alert_history', ['crop_instance_id'], unique=False)
    op.create_index(op.f('ix_pest_alert_history_is_deleted'), 'pest_alert_history', ['is_deleted'], unique=False)
    op.alter_column('provider_availability', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('provider_availability', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('provider_availability', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('provider_availability', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_provider_availability_is_deleted'), 'provider_availability', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_provider_availability_provider_id'), 'provider_availability', ['provider_id'], unique=False)
    op.alter_column('recommendations', 'priority_rank',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('recommendations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('recommendations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('recommendations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_recommendations_crop', table_name='recommendations')
    op.create_index(op.f('ix_recommendations_crop_instance_id'), 'recommendations', ['crop_instance_id'], unique=False)
    op.create_index(op.f('ix_recommendations_is_deleted'), 'recommendations', ['is_deleted'], unique=False)
    op.drop_constraint('recommendations_crop_instance_id_fkey', 'recommendations', type_='foreignkey')
    op.alter_column('regional_clusters', 'avg_delay',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('regional_clusters', 'avg_yield',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('regional_clusters', 'sample_size',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('regional_clusters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('regional_clusters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('regional_clusters', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_regional_clusters_crop_type'), 'regional_clusters', ['crop_type'], unique=False)
    op.create_index(op.f('ix_regional_clusters_is_deleted'), 'regional_clusters', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_regional_clusters_region'), 'regional_clusters', ['region'], unique=False)
    op.alter_column('regional_sowing_calendars', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('regional_sowing_calendars', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('regional_sowing_calendars', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('regional_sowing_calendars', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_sowing_cal_crop_region', table_name='regional_sowing_calendars')
    op.create_index(op.f('ix_regional_sowing_calendars_crop_type'), 'regional_sowing_calendars', ['crop_type'], unique=False)
    op.create_index(op.f('ix_regional_sowing_calendars_is_deleted'), 'regional_sowing_calendars', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_regional_sowing_calendars_region'), 'regional_sowing_calendars', ['region'], unique=False)
    op.alter_column('service_providers', 'trust_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0.5'::double precision"))
    op.alter_column('service_providers', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('service_providers', 'complaint_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('service_providers', 'completion_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('service_providers', 'resolution_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('service_providers', 'is_flagged',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('service_providers', 'is_suspended',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('service_providers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_providers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_providers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint('service_providers_user_id_key', 'service_providers', type_='unique')
    op.create_index(op.f('ix_service_providers_is_deleted'), 'service_providers', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_service_providers_region'), 'service_providers', ['region'], unique=False)
    op.create_index(op.f('ix_service_providers_service_type'), 'service_providers', ['service_type'], unique=False)
    op.create_index(op.f('ix_service_providers_user_id'), 'service_providers', ['user_id'], unique=True)
    op.alter_column('service_request_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_request_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_request_events', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_sre_request_id', table_name='service_request_events')
    op.create_index(op.f('ix_service_request_events_is_deleted'), 'service_request_events', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_service_request_events_request_id'), 'service_request_events', ['request_id'], unique=False)
    op.alter_column('service_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_requests', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_service_requests_farmer_id'), 'service_requests', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_service_requests_is_deleted'), 'service_requests', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_service_requests_provider_id'), 'service_requests', ['provider_id'], unique=False)
    op.create_index(op.f('ix_service_requests_status'), 'service_requests', ['status'], unique=False)
    op.alter_column('service_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_reviews', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint('service_reviews_request_id_key', 'service_reviews', type_='unique')
    op.create_index(op.f('ix_service_reviews_is_deleted'), 'service_reviews', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_service_reviews_request_id'), 'service_reviews', ['request_id'], unique=True)
    op.create_index(op.f('ix_service_reviews_reviewer_id'), 'service_reviews', ['reviewer_id'], unique=False)
    op.alter_column('stress_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stress_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stress_history', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_stress_history_crop_instance_id'), 'stress_history', ['crop_instance_id'], unique=False)
    op.create_index(op.f('ix_stress_history_is_deleted'), 'stress_history', ['is_deleted'], unique=False)
    op.alter_column('system_health', 'last_checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_health', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_health', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_health', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_system_health_is_deleted'), 'system_health', ['is_deleted'], unique=False)
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'en'::character varying"))
    op.alter_column('users', 'accessibility_settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('users', 'is_onboarded',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    op.drop_index('ix_users_phone', table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.alter_column('whatsapp_sessions', 'session_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('whatsapp_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('whatsapp_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('whatsapp_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('whatsapp_sessions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_whatsapp_sessions_phone', table_name='whatsapp_sessions')
    op.create_index(op.f('ix_whatsapp_sessions_farmer_phone'), 'whatsapp_sessions', ['farmer_phone'], unique=False)
    op.create_index(op.f('ix_whatsapp_sessions_is_deleted'), 'whatsapp_sessions', ['is_deleted'], unique=False)
    op.alter_column('yield_records', 'yield_unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'kg/acre'::character varying"))
    op.alter_column('yield_records', 'bio_cap_applied',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('yield_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('yield_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('yield_records', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_yield_records_crop_instance_id'), 'yield_records', ['crop_instance_id'], unique=False)
    op.create_index(op.f('ix_yield_records_is_deleted'), 'yield_records', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yield_records_is_deleted'), table_name='yield_records')
    op.drop_index(op.f('ix_yield_records_crop_instance_id'), table_name='yield_records')
    op.alter_column('yield_records', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('yield_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('yield_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('yield_records', 'bio_cap_applied',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('yield_records', 'yield_unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'kg/acre'::character varying"))
    op.drop_index(op.f('ix_whatsapp_sessions_is_deleted'), table_name='whatsapp_sessions')
    op.drop_index(op.f('ix_whatsapp_sessions_farmer_phone'), table_name='whatsapp_sessions')
    op.create_index('ix_whatsapp_sessions_phone', 'whatsapp_sessions', ['farmer_phone'], unique=False)
    op.alter_column('whatsapp_sessions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('whatsapp_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('whatsapp_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('whatsapp_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('whatsapp_sessions', 'session_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'general'::character varying"))
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_onboarded',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'accessibility_settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'en'::character varying"))
    op.drop_index(op.f('ix_system_health_is_deleted'), table_name='system_health')
    op.alter_column('system_health', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('system_health', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_health', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_health', 'last_checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_stress_history_is_deleted'), table_name='stress_history')
    op.drop_index(op.f('ix_stress_history_crop_instance_id'), table_name='stress_history')
    op.alter_column('stress_history', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('stress_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stress_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_service_reviews_reviewer_id'), table_name='service_reviews')
    op.drop_index(op.f('ix_service_reviews_request_id'), table_name='service_reviews')
    op.drop_index(op.f('ix_service_reviews_is_deleted'), table_name='service_reviews')
    op.create_unique_constraint('service_reviews_request_id_key', 'service_reviews', ['request_id'])
    op.alter_column('service_reviews', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('service_reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_service_requests_status'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_provider_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_is_deleted'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_farmer_id'), table_name='service_requests')
    op.alter_column('service_requests', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('service_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_service_request_events_request_id'), table_name='service_request_events')
    op.drop_index(op.f('ix_service_request_events_is_deleted'), table_name='service_request_events')
    op.create_index('ix_sre_request_id', 'service_request_events', ['request_id'], unique=False)
    op.alter_column('service_request_events', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('service_request_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_request_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_service_providers_user_id'), table_name='service_providers')
    op.drop_index(op.f('ix_service_providers_service_type'), table_name='service_providers')
    op.drop_index(op.f('ix_service_providers_region'), table_name='service_providers')
    op.drop_index(op.f('ix_service_providers_is_deleted'), table_name='service_providers')
    op.create_unique_constraint('service_providers_user_id_key', 'service_providers', ['user_id'])
    op.alter_column('service_providers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('service_providers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_providers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_providers', 'is_suspended',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('service_providers', 'is_flagged',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('service_providers', 'resolution_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('service_providers', 'completion_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('service_providers', 'complaint_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('service_providers', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('service_providers', 'trust_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0.5'::double precision"))
    op.drop_index(op.f('ix_regional_sowing_calendars_region'), table_name='regional_sowing_calendars')
    op.drop_index(op.f('ix_regional_sowing_calendars_is_deleted'), table_name='regional_sowing_calendars')
    op.drop_index(op.f('ix_regional_sowing_calendars_crop_type'), table_name='regional_sowing_calendars')
    op.create_index('ix_sowing_cal_crop_region', 'regional_sowing_calendars', ['crop_type', 'region'], unique=False)
    op.alter_column('regional_sowing_calendars', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('regional_sowing_calendars', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('regional_sowing_calendars', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('regional_sowing_calendars', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_regional_clusters_region'), table_name='regional_clusters')
    op.drop_index(op.f('ix_regional_clusters_is_deleted'), table_name='regional_clusters')
    op.drop_index(op.f('ix_regional_clusters_crop_type'), table_name='regional_clusters')
    op.alter_column('regional_clusters', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('regional_clusters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('regional_clusters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('regional_clusters', 'sample_size',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('regional_clusters', 'avg_yield',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('regional_clusters', 'avg_delay',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.create_foreign_key('recommendations_crop_instance_id_fkey', 'recommendations', 'crop_instances', ['crop_instance_id'], ['id'])
    op.drop_index(op.f('ix_recommendations_is_deleted'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_crop_instance_id'), table_name='recommendations')
    op.create_index('ix_recommendations_crop', 'recommendations', ['crop_instance_id'], unique=False)
    op.alter_column('recommendations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('recommendations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('recommendations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('recommendations', 'priority_rank',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_provider_availability_provider_id'), table_name='provider_availability')
    op.drop_index(op.f('ix_provider_availability_is_deleted'), table_name='provider_availability')
    op.alter_column('provider_availability', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('provider_availability', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('provider_availability', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('provider_availability', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_pest_alert_history_is_deleted'), table_name='pest_alert_history')
    op.drop_index(op.f('ix_pest_alert_history_crop_instance_id'), table_name='pest_alert_history')
    op.create_index('ix_pest_alert_crop', 'pest_alert_history', ['crop_instance_id'], unique=False)
    op.alter_column('pest_alert_history', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('pest_alert_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pest_alert_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pest_alert_history', 'detected_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('pest_alert_history', 'alert_level',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Low'::character varying"))
    op.drop_index(op.f('ix_ml_training_audit_model_id'), table_name='ml_training_audit')
    op.drop_index(op.f('ix_ml_training_audit_is_deleted'), table_name='ml_training_audit')
    op.alter_column('ml_training_audit', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('ml_training_audit', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ml_training_audit', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ml_models_model_name'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_is_deleted'), table_name='ml_models')
    op.alter_column('ml_models', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('ml_models', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ml_models', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ml_models', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('ml_models', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_ml_feedback_is_deleted'), table_name='ml_feedback')
    op.drop_index(op.f('ix_ml_feedback_crop_instance_id'), table_name='ml_feedback')
    op.create_index('ix_ml_feedback_crop', 'ml_feedback', ['crop_instance_id'], unique=False)
    op.alter_column('ml_feedback', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('ml_feedback', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ml_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_media_files_is_deleted'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_crop_instance_id'), table_name='media_files')
    op.alter_column('media_files', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('media_files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('media_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('media_files', 'geo_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('media_files', 'analysis_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_market_prices_is_deleted'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_crop_type'), table_name='market_prices')
    op.create_index('ix_market_prices_crop', 'market_prices', ['crop_type'], unique=False)
    op.alter_column('market_prices', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('market_prices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('market_prices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('market_prices', 'is_stale',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('market_prices', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'INR'::character varying"))
    op.alter_column('market_prices', 'unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'kg'::character varying"))
    op.drop_index(op.f('ix_land_parcels_is_deleted'), table_name='land_parcels')
    op.drop_index(op.f('ix_land_parcels_farmer_id'), table_name='land_parcels')
    op.create_index('ix_land_parcels_farmer', 'land_parcels', ['farmer_id'], unique=False)
    op.alter_column('land_parcels', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('land_parcels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('land_parcels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_labor_provider_id'), table_name='labor')
    op.drop_index(op.f('ix_labor_is_deleted'), table_name='labor')
    op.create_index('ix_labor_provider', 'labor', ['provider_id'], unique=False)
    op.alter_column('labor', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('labor', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('labor', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('labor', 'is_flagged',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('labor', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('labor', 'available_units',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_feature_flags_is_deleted'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_flag_name'), table_name='feature_flags')
    op.create_unique_constraint('feature_flags_flag_name_key', 'feature_flags', ['flag_name'])
    op.alter_column('feature_flags', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('feature_flags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('feature_flags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('feature_flags', 'scope',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'global'::character varying"))
    op.alter_column('feature_flags', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_farmer_action_audit_log_is_deleted'), table_name='farmer_action_audit_log')
    op.drop_index(op.f('ix_farmer_action_audit_log_farmer_id'), table_name='farmer_action_audit_log')
    op.drop_index(op.f('ix_farmer_action_audit_log_action_type'), table_name='farmer_action_audit_log')
    op.create_index('ix_farmer_audit_farmer', 'farmer_action_audit_log', ['farmer_id'], unique=False)
    op.create_index('ix_farmer_audit_action', 'farmer_action_audit_log', ['action_type'], unique=False)
    op.alter_column('farmer_action_audit_log', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('farmer_action_audit_log', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('farmer_action_audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_event_log_is_deleted'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_event_type'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_entity_id'), table_name='event_log')
    op.alter_column('event_log', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('event_log', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('event_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('event_log', 'max_retries',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('event_log', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('event_log', 'schema_version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('event_log', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
    op.alter_column('event_log', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_equipment_provider_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_is_deleted'), table_name='equipment')
    op.alter_column('equipment', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('equipment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('equipment', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('equipment', 'is_flagged',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('equipment', 'condition',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'good'::character varying"))
    op.alter_column('equipment', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_deviation_profiles_is_deleted'), table_name='deviation_profiles')
    op.drop_index(op.f('ix_deviation_profiles_crop_instance_id'), table_name='deviation_profiles')
    op.create_unique_constraint('deviation_profiles_crop_instance_id_key', 'deviation_profiles', ['crop_instance_id'])
    op.alter_column('deviation_profiles', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('deviation_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('deviation_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('deviation_profiles', 'recurring_pattern_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('deviation_profiles', 'deviation_trend_slope',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('deviation_profiles', 'consecutive_deviation_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_deviation_profile_archive_is_deleted'), table_name='deviation_profile_archive')
    op.drop_index(op.f('ix_deviation_profile_archive_farmer_id'), table_name='deviation_profile_archive')
    op.create_index('ix_deviation_archive_farmer', 'deviation_profile_archive', ['farmer_id'], unique=False)
    op.alter_column('deviation_profile_archive', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('deviation_profile_archive', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('deviation_profile_archive', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('deviation_profile_archive', 'archived_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('crop_rule_templates', sa.Column('is_active', sa.VARCHAR(length=10), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_crop_rule_templates_is_deleted'), table_name='crop_rule_templates')
    op.alter_column('crop_rule_templates', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('crop_rule_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('crop_rule_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('crop_rule_templates', 'risk_parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('crop_rule_templates', 'stage_definitions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_column('crop_rule_templates', 'validation_errors')
    op.drop_column('crop_rule_templates', 'approved_at')
    op.drop_column('crop_rule_templates', 'approved_by')
    op.drop_column('crop_rule_templates', 'status')
    op.drop_index(op.f('ix_crop_instances_is_deleted'), table_name='crop_instances')
    op.create_index('ix_crop_instances_land_parcel_id', 'crop_instances', ['land_parcel_id'], unique=False)
    op.alter_column('crop_instances', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('crop_instances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('crop_instances', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('crop_instances', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('crop_instances', 'risk_index',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('crop_instances', 'stress_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.drop_column('crop_instances', 'projected_harvest_date')
    op.drop_index(op.f('ix_crop_instance_snapshots_is_deleted'), table_name='crop_instance_snapshots')
    op.drop_index(op.f('ix_crop_instance_snapshots_crop_instance_id'), table_name='crop_instance_snapshots')
    op.alter_column('crop_instance_snapshots', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('crop_instance_snapshots', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('crop_instance_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('crop_instance_snapshots', 'snapshot_version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_backup_verification_logs_is_deleted'), table_name='backup_verification_logs')
    op.alter_column('backup_verification_logs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('backup_verification_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_verification_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_verification_logs', 'result',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('backup_verification_logs', 'restore_tested',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('backup_verification_logs', 'backup_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'full'::character varying"))
    op.alter_column('backup_verification_logs', 'backup_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_alerts_is_deleted'), table_name='alerts')
    op.alter_column('alerts', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('alerts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('alerts', 'is_acknowledged',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'info'::character varying"))
    op.drop_index(op.f('ix_admin_audit_log_is_deleted'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_admin_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_action'), table_name='admin_audit_log')
    op.alter_column('admin_audit_log', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('admin_audit_log', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('admin_audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_action_logs_is_deleted'), table_name='action_logs')
    op.alter_column('action_logs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('action_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('action_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('action_logs', 'server_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('action_logs', 'is_orphaned',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('action_logs', 'is_override',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('action_logs', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'web'::character varying"))
    op.alter_column('action_logs', 'action_impact_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Operational'::character varying"))
    op.drop_index(op.f('ix_abuse_flags_is_deleted'), table_name='abuse_flags')
    op.drop_index(op.f('ix_abuse_flags_flag_type'), table_name='abuse_flags')
    op.drop_index(op.f('ix_abuse_flags_farmer_id'), table_name='abuse_flags')
    op.alter_column('abuse_flags', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('abuse_flags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('abuse_flags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('abuse_flags', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('abuse_flags', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'low'::character varying"))
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('otp_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='otp_codes_pkey')
    )
    op.create_index('ix_otp_codes_phone', 'otp_codes', ['phone'], unique=False)
    op.create_table('active_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('device_fingerprint', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='active_sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='active_sessions_pkey'),
    sa.UniqueConstraint('refresh_token_hash', name='active_sessions_refresh_token_hash_key')
    )
    op.create_index('ix_active_sessions_user_id', 'active_sessions', ['user_id'], unique=False)
    op.create_index('ix_active_sessions_refresh_token_hash', 'active_sessions', ['refresh_token_hash'], unique=False)
    op.create_index('ix_active_sessions_is_revoked', 'active_sessions', ['is_revoked'], unique=False)
    op.drop_index(op.f('ix_weather_snapshots_location_key'), table_name='weather_snapshots')
    op.drop_index(op.f('ix_weather_snapshots_expires_at'), table_name='weather_snapshots')
    op.drop_index(op.f('ix_weather_snapshots_captured_at'), table_name='weather_snapshots')
    op.drop_table('weather_snapshots')
    # ### end Alembic commands ###
