"""add_ml_inference_audit

Revision ID: f9fb64385d37
Revises: 013_trust_defaults
Create Date: 2026-04-09 01:18:06.590208
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f9fb64385d37'
down_revision: Union[str, None] = '013_trust_defaults'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
